### ISSUE TITLE
Outdated Yocto requirements

### ISSUE THREAD

**Issue by zaid11imroz** [nxp-auto-linux/auto_yocto_bsp#4]
The required packages mentioned in the file "/sources/meta-alb/scripts/host-prepare-ubuntu-mint-debian.sh" are outdated.
The packages "python2" and "lz4" are not found in the apt repository anymore. They are not required by Yocto as well.

The new package name for "python2" is "python" in the apt repository.
The package name for "lz4" is not known but could possibly be "liblz4".

This has to be corrected based on the updated Yocto project requirements otherwise the script fails to execute.

**Comment by catalinudmanxp** [comment]
The package names depend on the Ubuntu version on the host build machine. The names are aligned with the Ubuntu host version mentioned in the Linux BSP User Manual, and, as you mentioned, they don't apply to any Ubuntu version.
