### ISSUE TITLE
Login for `s32g274ardb2ubuntu` image

### ISSUE THREAD

**Issue by gitbelg** [nxp-auto-linux/auto_yocto_bsp#5]
Hello,

I recently installed the `s32g274ardb2ubuntu` image from 38.0 release. After booting up, I am asked for login credentials, but I can not find any document referencing the default password. Can someone provide me with the username/password?

**Comment by recyclebin99** [comment]
At least as of BSP35, the Ubuntu Yocto build uses:

user: bluebox
password: bluebox

(from 'S32G3_LinuxBSP_35.0_User_Manual.pdf', section 3.1.3)
